package com.domain.entity;

public class Newtable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newtable.id
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newtable.name
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newtable.age
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newtable.id
     *
     * @return the value of newtable.id
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newtable.id
     *
     * @param id the value for newtable.id
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newtable.name
     *
     * @return the value of newtable.name
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newtable.name
     *
     * @param name the value for newtable.name
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newtable.age
     *
     * @return the value of newtable.age
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newtable.age
     *
     * @param age the value for newtable.age
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}