package com.domain.mapper;

import com.domain.entity.Newtable;
import com.domain.entity.NewtableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewtableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    long countByExample(NewtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int deleteByExample(NewtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int insert(Newtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int insertSelective(Newtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    List<Newtable> selectByExample(NewtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    Newtable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int updateByExampleSelective(@Param("record") Newtable record, @Param("example") NewtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int updateByExample(@Param("record") Newtable record, @Param("example") NewtableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int updateByPrimaryKeySelective(Newtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newtable
     *
     * @mbg.generated Sun Apr 02 16:03:39 CEST 2017
     */
    int updateByPrimaryKey(Newtable record);
}